# Copyright (C) 2014 the2nd <the2nd@otpme.org>
""" Spread LDAP requests over the ldapd of every member node.

Runs on the node that holds the floating IP, so controld starts and
stops it where it configures that IP -- and as root, which is what
binding port 636 takes. haproxy drops to the OTPme user itself.

The backends are the member nodes clusterd knows about, addressed by
their FQDN: OTPme does not keep node addresses, that is all DNS.
"""

import os
import time

from otpme.lib import net
from otpme.lib import stuff
from otpme.lib import config
from otpme.lib import locking
from otpme.lib import backend
from otpme.lib import filetools
from otpme.lib import multiprocessing
from otpme.lib import system_command

from otpme.lib.exceptions import *

haproxy_dir = os.path.join(config.run_dir, "haproxy")
haproxy_conf = os.path.join(haproxy_dir, "haproxy.cfg")
haproxy_custom_conf = os.path.join(config.config_dir, "haproxy", "haproxy.cfg")
haproxy_pidfile = os.path.join(config.pidfile_dir, "haproxy.pid")

LOCK_TYPE = "haproxy"
locking.register_lock_type(LOCK_TYPE, module=__file__)

# mode tcp: the backend speaks LDAPS and answers with the site
# certificate, so there is nothing for us to terminate or to look into.
# It also keeps the "dc=<client>" of a bind DN intact, which is how
# OTPme picks the accessgroup.
#
# The client address is lost this way. ldapd does not use it: it reads
# the peer in OTPmeLDAPServer.connectionMade() and hands it to the
# entry, and nothing ever reads it back. Do not put a daemon behind
# this that does, authd for one decides by peer type.
#
# No "pidfile" here: we pass it with "-p" so it also holds for a custom
# config, and haproxy takes the two as a redefinition.
#
# No "option tcplog" either as long as there is no "log" address. It
# would only earn us a warning per start, and haproxy has no way to log
# to a plain file: its "log" takes a syslog socket, an address or a file
# descriptor, and in daemon mode stdout is gone.
HAPROXY_CONF_TEMPLATE = '''# Generated by OTPme. Do not edit.
global
    daemon
    maxconn {maxconn}
    user {user}
    group {group}

defaults
    mode tcp
    timeout connect {connect_timeout}
    timeout client {client_timeout}
    timeout server {server_timeout}

frontend ldaps
    bind {listen}
    default_backend ldapd

backend ldapd
    balance leastconn
    option tcp-check
{servers}
'''

# One line per member node. "check" is a plain TCP connect: the backend
# would have to do the TLS handshake for anything more, and a node that
# accepts connections is what we want to know.
HAPROXY_SERVER_TEMPLATE = ("    server {name} {fqdn}:{port} check"
                        " inter {interval} fall 3 rise 2")


def get_member_nodes():
    """ Get the nodes to send requests to.

    Ourselves included: we hold the floating IP, but our own ldapd
    answers requests like every other one.
    """
    node_names = set()
    try:
        own_node = backend.get_object(uuid=config.uuid)
    except Exception as e:
        own_node = None
        log_msg = _("Failed to get own node: {error}", log=True)[1]
        log_msg = log_msg.format(error=e)
        config.logger.warning(log_msg)
    if own_node:
        node_names.add(own_node.name)
    try:
        node_names.update(multiprocessing.member_nodes)
    except Exception as e:
        log_msg = _("Failed to get member nodes: {error}", log=True)[1]
        log_msg = log_msg.format(error=e)
        config.logger.warning(log_msg)
    nodes = []
    for x_name in sorted(node_names):
        result = backend.search(object_type="node",
                                attribute="name",
                                value=x_name,
                                return_type="instance")
        if not result:
            log_msg = _("Unknown member node: {node}", log=True)[1]
            log_msg = log_msg.format(node=x_name)
            config.logger.warning(log_msg)
            continue
        x_node = result[0]
        if not x_node.enabled:
            continue
        nodes.append((x_node.name, x_node.fqdn))
    return nodes


def create_haproxy_conf():
    """ Write the config haproxy runs with. """
    if not os.path.exists(haproxy_dir):
        filetools.create_dir(haproxy_dir,
                            user=config.user,
                            group=config.group,
                            mode=0o770)

    if os.path.exists(haproxy_custom_conf):
        # An admin who wants something else keeps it, we only put it in
        # place. The member nodes are not in there then either.
        import shutil
        shutil.copyfile(haproxy_custom_conf, haproxy_conf)
        return

    nodes = get_member_nodes()
    if not nodes:
        msg = _("Refusing to write haproxy config without a member node.")
        raise OTPmeException(msg)

    ldapd_port = config.default_ports['ldapd']
    servers = []
    for x_name, x_fqdn in nodes:
        servers.append(HAPROXY_SERVER_TEMPLATE.format(name=x_name,
                                        fqdn=x_fqdn,
                                        port=ldapd_port,
                                        interval=config.haproxy_check_interval))

    # The site address is a bare IP, of either family. haproxy takes an
    # IPv6 literal in brackets only, an IPv4 one only without.
    if not config.site_address:
        msg = _("Refusing to write haproxy config without a site address.")
        raise OTPmeException(msg)
    if not net.is_ip(config.site_address):
        msg = _("Site address is not an IP address: {address}")
        msg = msg.format(address=config.site_address)
        raise OTPmeException(msg)
    listen = net.format_host_port(config.site_address, config.haproxy_port)

    haproxy_config = HAPROXY_CONF_TEMPLATE.format(
                            maxconn=config.haproxy_maxconn,
                            user=config.user,
                            group=config.group,
                            connect_timeout=config.haproxy_connect_timeout,
                            client_timeout=config.haproxy_client_timeout,
                            server_timeout=config.haproxy_server_timeout,
                            listen=listen,
                            servers="\n".join(servers))

    filetools.create_file(haproxy_conf,
                        content=haproxy_config,
                        mode=0o660)


def get_pid():
    fd = open(haproxy_pidfile, "r")
    pid = fd.read().replace("\n", "")
    fd.close()
    return pid


def status():
    if not os.path.exists(haproxy_pidfile):
        msg = _("Haproxy not running.")
        raise NotRunning(msg)
    pid = get_pid()
    if not stuff.check_pid(pid):
        msg = _("Haproxy not running.")
        raise NotRunning(msg)
    return True


def start():
    """ Start haproxy. """
    try:
        status()
        haproxy_running = True
    except Exception:
        haproxy_running = False
    if haproxy_running:
        msg = _("Haproxy already running.")
        raise AlreadyRunning(msg)
    lock_caller = "start"
    lock = locking.acquire_lock(lock_type=LOCK_TYPE,
                                lock_id=lock_caller,
                                lock_caller=lock_caller,
                                write=True, timeout=10)
    try:
        create_haproxy_conf()
        # No user/group here on purpose: binding port 636 needs the
        # privileges of our caller, and haproxy gives them up itself,
        # see the "user"/"group" of the config we write.
        start_cmd = [config.haproxy_bin, "-f", haproxy_conf,
                    "-p", haproxy_pidfile]
        # haproxy daemonizes, so this waits for the forking parent only
        # and we get its exit code. Without it a config haproxy refuses
        # (a floating IP it cannot bind, for one) would fail silently.
        returncode = system_command.run(command=start_cmd,
                                        close_fds=True,
                                        shell=False,
                                        call=True)
        if returncode != 0:
            msg = _("Haproxy failed to start: exit code {returncode}. See its output for the reason.")
            msg = msg.format(returncode=returncode)
            raise OTPmeException(msg)
    finally:
        lock.release_lock(lock_caller=lock_caller)


def stop():
    """ Stop haproxy. """
    try:
        status()
    except Exception:
        return
    pid = get_pid()
    stuff.kill_pid(pid)
    while stuff.check_pid(pid):
        time.sleep(0.1)


def reload():
    """ Hand the connections over to a haproxy with the new config.

    A member node came or went, so the backends changed. "-sf" lets the
    running process finish what it has in flight while the new one
    takes the socket, so nobody gets a reset.
    """
    try:
        status()
    except Exception:
        msg = _("Haproxy not running.")
        raise NotRunning(msg)
    lock_caller = "reload"
    lock = locking.acquire_lock(lock_type=LOCK_TYPE,
                                lock_id=lock_caller,
                                lock_caller=lock_caller,
                                write=True, timeout=10)
    try:
        old_pid = get_pid()
        create_haproxy_conf()
        start_cmd = [config.haproxy_bin, "-f", haproxy_conf,
                    "-p", haproxy_pidfile, "-sf", str(old_pid)]
        returncode = system_command.run(command=start_cmd,
                                        close_fds=True,
                                        shell=False,
                                        call=True)
        if returncode != 0:
            msg = _("Haproxy failed to reload: exit code {returncode}. The running one keeps the connections.")
            msg = msg.format(returncode=returncode)
            raise OTPmeException(msg)
    finally:
        lock.release_lock(lock_caller=lock_caller)
