# -*- coding: utf-8 -*-
# Copyright (C) 2014 the2nd <the2nd@otpme.org>
""" tiqr token (https://tiqr.org).

Challenge-response against a shared secret using OCRA (RFC 6287). The
server shows a challenge as a QR code or a tiqrauth:// link, the phone
computes the response with the secret it holds and posts it back over
its own connection.

Unlike every other token type here the secret is generated by the
*phone* and handed to us during enrollment, so a freshly added token
carries no secret until an app has been through it. Everything that
drives that -- the enrollment and authentication flow, the endpoints the
phone talks to -- lives outside this class; this is the stored
credential and the OCRA check on it, nothing else.

What this token is worth, so nobody mistakes it for more: the response
is one-time and challenge-bound, so it beats a password and cannot be
replayed. But it is NOT phishing resistant. Nothing in the protocol ties
the response to the browser's origin -- the phone answers over its own
channel and never learns where the browser is -- so an attacker who
relays a genuine challenge onto their own page gets the user's
confirmation for their own session. Same class as TOTP and push
approval; fido2/passkey are the phishing-resistant option here. On top
of that the server has to keep the secret recoverable to verify a
response, so a database breach exposes every tiqr credential, which is
not true for passkeys.
"""
import os

from typing import Union

try:
    if os.environ['OTPME_DEBUG_MODULE_LOADING'] == "True":
        msg = _("Loading module: {module_name}")
        msg = msg.format(module_name=__name__)
        print(msg)
except Exception:
    pass

from otpme.lib import oid
from otpme.lib import stuff
from otpme.lib import config
from otpme.lib import backend
from otpme.lib import otpme_acl
from otpme.lib.otp.oath import ocra
from otpme.lib.classes.token import Token
from otpme.lib.locking import object_lock
from otpme.lib.job.callback import JobCallback
from otpme.lib.typing import match_class_typing
from otpme.lib.protocols.utils import register_commands
from otpme.lib.protocols import tiqr_helpers

from otpme.lib.classes.token \
            import get_acls \
            as _get_acls
from otpme.lib.classes.token \
            import get_value_acls \
            as _get_value_acls
from otpme.lib.classes.token \
            import get_default_acls \
            as _get_default_acls
from otpme.lib.classes.token \
            import get_recursive_default_acls \
            as _get_recursive_default_acls

from otpme.lib.exceptions import *

default_callback = config.get_callback()

logger = config.logger

# The suite tiqr has used since day one. "-S" without a length is a
# deviation from RFC 6287 that both the tiqr server library and the tiqr
# apps implement; see otpme/lib/otp/oath/ocra.py. The apps store the
# suite at enrollment and cannot be told a different one afterwards,
# which is why every token keeps its own copy.
DEFAULT_OCRA_SUITE = "OCRA-1:HOTP-SHA1-6:QH10-S"

# Custom URL schemes the stock tiqr apps register. Universal links would
# need the app to be associated with our domain, which only works for an
# app you build and publish yourself, so the schemes are what we use.
DEFAULT_AUTH_SCHEME = "tiqrauth"
DEFAULT_ENROLL_SCHEME = "tiqrenroll"

# Lifetimes in seconds, taken from Tiqr_Service of the reference
# implementation: three minutes to answer a challenge, five to walk
# through an enrollment.
DEFAULT_CHALLENGE_EXPIRY = 180
DEFAULT_ENROLLMENT_EXPIRY = 300

read_acls =  []
write_acls =  []

read_value_acls = {
                "view"      : [
                            "secret",
                            "ocra_suite",
                            "identity_id",
                            "notification_type",
                            "notification_address",
                            "auth_script",
                            "offline_status",
                            "offline_expiry",
                            "offline_unused_expiry",
                            "session_keep",
                            ],
                }

write_value_acls = {
                "edit"      : [
                            "auth_script",
                            "offline_expiry",
                            "offline_unused_expiry",
                            ],
                "enable"    : [
                            "auth_script",
                            "offline",
                            "session_keep",
                            ],
                "disable"   : [
                            "auth_script",
                            "offline",
                            "session_keep",
                            ],
                }

default_acls = []

recursive_default_acls = []

# Enrollment runs through the browser and the phone, like passkeys, so
# there is no CLI deploy or test command.
commands = {}

def get_acls(split=False, **kwargs):
    """ Get all supported object ACLs """
    if split:
        otpme_token_read_acls, \
        otpme_token_write_acls = _get_acls(split=split, **kwargs)
        _read_acls = otpme_acl.merge_acls(read_acls, otpme_token_read_acls)
        _write_acls = otpme_acl.merge_acls(write_acls, otpme_token_write_acls)
        return _read_acls, _write_acls
    otpme_token_acls = _get_acls(**kwargs)
    _acls = otpme_acl.merge_acls(read_acls, write_acls)
    _acls = otpme_acl.merge_acls(_acls, otpme_token_acls)
    return _acls

def get_value_acls(split=False, **kwargs):
    """ Get all supported object value ACLs """
    if split:
        otpme_token_read_value_acls, \
        otpme_token_write_value_acls = _get_value_acls(split=split, **kwargs)
        _read_value_acls = otpme_acl.merge_value_acls(read_value_acls,
                                                    otpme_token_read_value_acls)
        _write_value__acls = otpme_acl.merge_value_acls(write_value_acls,
                                                        otpme_token_write_value_acls)
        return _read_value_acls, _write_value__acls
    otpme_token_value_acls = _get_value_acls(**kwargs)
    _acls = otpme_acl.merge_value_acls(read_value_acls, write_value_acls)
    _acls = otpme_acl.merge_value_acls(_acls, otpme_token_value_acls)
    return _acls

def get_default_acls():
    """ Get all supported object default ACLs """
    token_default_acls = _get_default_acls()
    _acls = otpme_acl.merge_acls(default_acls, token_default_acls)
    return _acls

def get_recursive_default_acls():
    """ Get all supported object recursive default ACLs """
    token_recursive_default_acls = _get_recursive_default_acls()
    _acls = otpme_acl.merge_acls(recursive_default_acls,
                                token_recursive_default_acls)
    return _acls

REGISTER_BEFORE = []
REGISTER_AFTER = []

def register():
    """ Register object. """
    register_token_type()
    register_commands("token",
                    commands,
                    sub_type="tiqr",
                    sub_type_attribute="token_type")
    register_config_parameters()

def register_token_type():
    """ Register token type. """
    config.register_sub_object_type("token", "tiqr")

# Per-process cache for the site's tiqr HMAC secret. Every tiqr request
# needs it, and it only changes when an admin rotates it. Reset to None
# on fork; the child re-reads lazily.
_SITE_SECRET_CACHE = None

def get_site_secret():
    """ The site's tiqr HMAC secret.

    Replicated with the site object, so every node derives the same
    challenge, poll id and enrollment key -- which is what lets the
    phone reach one node and the browser another. """
    global _SITE_SECRET_CACHE
    if _SITE_SECRET_CACHE is not None:
        return _SITE_SECRET_CACHE
    site = backend.get_object(object_type="site", uuid=config.site_uuid)
    if site is None:
        msg = _("tiqr: site object not found.")
        raise OTPmeException(msg)
    secret = getattr(site, 'tiqr_secret', None)
    if not secret:
        msg = _("Site '{site}' has no tiqr secret. Run 'otpme-site tiqr_secret {site}'.")
        msg = msg.format(site=site.name)
        raise OTPmeException(msg)
    _SITE_SECRET_CACHE = secret
    return _SITE_SECRET_CACHE

def register_config_parameters():
    """ Register config parameters. """
    # What a new enrollment offers the app. The suite a token actually
    # uses is stored on the token itself, because the apps bake it into
    # the account at enrollment and changing this must not invalidate
    # phones that were enrolled under the old one.
    config.register_config_parameter(name="tiqr_ocra_suite",
                                    ctype=str,
                                    default_value=DEFAULT_OCRA_SUITE,
                                    object_types=['site', 'unit', 'user'])
    # Shown by the app as the name of the service. Empty means the realm
    # name is used.
    #
    # Checked on the way in rather than worked around later: the mistake
    # it catches would otherwise surface at the first login, as an
    # unrelated-looking error, with nothing pointing back at this
    # parameter. See tiqr_helpers.validate_service_display_name().
    def service_display_name_setter(display_name, **kwargs):
        tiqr_helpers.validate_service_display_name(display_name)
        return display_name
    config.register_config_parameter(name="tiqr_service_display_name",
                                    ctype=str,
                                    default_value=None,
                                    setter=service_display_name_setter,
                                    object_types=['site'])
    # Have to match the app that is handed out; the stock apps use these.
    config.register_config_parameter(name="tiqr_auth_scheme",
                                    ctype=str,
                                    default_value=DEFAULT_AUTH_SCHEME,
                                    object_types=['site'])
    config.register_config_parameter(name="tiqr_enroll_scheme",
                                    ctype=str,
                                    default_value=DEFAULT_ENROLL_SCHEME,
                                    object_types=['site'])
    config.register_config_parameter(name="tiqr_challenge_expiry",
                                    ctype=int,
                                    default_value=DEFAULT_CHALLENGE_EXPIRY,
                                    object_types=['site', 'unit', 'user'])
    config.register_config_parameter(name="tiqr_enrollment_expiry",
                                    ctype=int,
                                    default_value=DEFAULT_ENROLLMENT_EXPIRY,
                                    object_types=['site', 'unit', 'user'])
    # There is deliberately no per-challenge attempt counter here.
    # Counting wrong responses means writing state that every node can
    # see, keyed by a session key anyone can mint at /login/tiqr/begin
    # -- unauthenticated writes with nothing to clean them up, which is
    # what this whole design avoids. Guessing is bounded by the rate
    # limit on /tiqr/auth together with tiqr_challenge_expiry instead;
    # see the note at _RATE_LIMIT_TIQR in otpme/web/app/tiqr/views.py.


@match_class_typing
class TiqrToken(Token):
    """ Class for tiqr tokens. """
    commands = commands
    # RFC 8176. "otp": the response is a one-time password. "mca": the
    # challenge goes out over the browser and comes back over the
    # phone's own channel. "user": a response only exists because
    # someone confirmed it in the app.
    #
    # Deliberately NOT "mfa": the tiqr apps do unlock the secret with a
    # PIN, but the protocol carries no signal about it, so we cannot
    # tell a genuine app from a client that stored the secret in the
    # clear. Claiming a factor we cannot observe would mislead every
    # relying party that reads amr.
    oidc_amr_values = ['otp', 'mca', 'user']
    def __init__(
        self,
        object_id: Union[oid.OTPmeOid,None]=None,
        user: Union[str,None]=None,
        name: Union[str,None]=None,
        realm: Union[str,None]=None,
        site: Union[str,None]=None,
        path: Union[str,None]=None,
        **kwargs,
        ):
        # Call parent class init.
        super().__init__(object_id=object_id,
                                            realm=realm,
                                            site=site,
                                            user=user,
                                            name=name,
                                            path=path,
                                            **kwargs)

        self._acls = get_acls()
        self._value_acls = get_value_acls()
        self._default_acls = get_default_acls()
        self._recursive_default_acls = get_recursive_default_acls()
        # Set token type.
        self.token_type = "tiqr"
        # Not a password the user types: the app answers a challenge out
        # of band. Its own pass type rather than "smartcard", because no
        # card is involved and the material reaches verify() through
        # token_auth_data instead -- AuthHandler handles the two side by
        # side.
        self.pass_type = "tiqr"
        # An OCRA response, valid for one server-issued challenge only.
        # A wrong answer to one challenge says nothing about the next,
        # so counting across them measures nothing -- and /tiqr/auth is
        # unauthenticated, so it would hand anybody a lockout lever.
        # What bounds guessing here is the rate limit on that route
        # together with tiqr_challenge_expiry.
        self.count_fails = False
        # The OCRA suite this token was enrolled with. Per token because
        # the suite string goes into the HMAC, so a token enrolled under
        # one suite can never be verified under another.
        self.ocra_suite = None
        # What the app sends back as "userId".
        self.identity_id = None
        # device_name -- what the user calls this phone -- comes from
        # the base class: every token type the portal hands out carries
        # one, not just this one.
        # Push details the app offers at enrollment. Stored so a later
        # push implementation finds them; nothing sends anything yet,
        # and it could not: pushing to the stock app would need SURF's
        # APNS/FCM credentials.
        self.notification_type = None
        self.notification_address = None
        # Token deploy finished?
        self.deployed = False
        # Verifying needs the server side secret and a server issued
        # challenge, so there is nothing to do offline.
        self.allow_offline = False
        self.offline_expiry = 0
        self.offline_unused_expiry = 0
        self.keep_session = False
        self.offline_pinnable = False
        self.supported_hardware_tokens = ['tiqr']
        self._sub_sync_fields = {
                    'host'  : {
                        'trusted'  : [
                            "DEPLOYED",
                            "OCRA_SUITE",
                            ]
                        },

                    'node'  : {
                        'untrusted'  : [
                            "DEPLOYED",
                            "OCRA_SUITE",
                            ]
                        },
                    }


    def _get_object_config(self):
        """ Merge token config with config from parent class. """
        # SECRET is inherited from the base object config, where it is
        # already encrypted on disk (otpme_object.py).
        token_config = {
            'OCRA_SUITE'                : {
                                            'var_name'      : 'ocra_suite',
                                            'type'          : str,
                                            'required'      : False,
                                        },

            'IDENTITY_ID'               : {
                                            'var_name'      : 'identity_id',
                                            'type'          : str,
                                            'required'      : False,
                                        },

            'NOTIFICATION_TYPE'         : {
                                            'var_name'      : 'notification_type',
                                            'type'          : str,
                                            'required'      : False,
                                        },

            'NOTIFICATION_ADDRESS'      : {
                                            'var_name'      : 'notification_address',
                                            'type'          : str,
                                            'required'      : False,
                                            'encryption'    : config.disk_encryption,
                                        },

            'DEPLOYED'                  : {
                                            'var_name'      : 'deployed',
                                            'type'          : bool,
                                            'required'      : False,
                                        },

            }
        return Token._get_object_config(self, token_config=token_config)

    def _get_token_data_attrs(self):
        """ Attributes copied by dump/set_token_data. """
        return [
                'secret',
                'ocra_suite',
                'identity_id',
                ]

    @property
    def need_password(self):
        # The app holds the secret and unlocks it with its own PIN; there
        # is no OTPme side password.
        return False

    @need_password.setter
    def need_password(self, *args, **kwargs):
        return

    def has_auth_data(self):
        """ Has a phone been through enrollment for this token? """
        if not self.secret:
            return False
        if not self.ocra_suite:
            return False
        return True

    def verify_ocra(self, challenge: str, session_key: str, response: str):
        """ Check an OCRA response against this token's secret.

        Only the arithmetic, and deliberately stateless: the same inputs
        always give the same verdict. Replay protection is NOT done here
        -- a bare six digit response is not a usable key for the used-OTP
        store, because collisions across challenges would lock people
        out. It is the caller that has to make a challenge answerable
        only once. """
        if not self.has_auth_data():
            log_msg = _("Token not deployed: {token_path}", log=True)[1]
            log_msg = log_msg.format(token_path=self.rel_path)
            logger.warning(log_msg)
            return False
        try:
            verify_status = ocra.verify(self.ocra_suite,
                                        self.secret,
                                        challenge,
                                        response,
                                        session=session_key)
        except OTPmeException as e:
            log_msg = _("Token verification failed: {error}", log=True)[1]
            log_msg = log_msg.format(error=e)
            logger.warning(log_msg)
            return False
        return verify_status

    # No cleanup of answered logins here any more, and nothing to drop
    # when the token goes: an answered login lives in the
    # tiqr_auth_results shared dict with a TTL of its challenge window,
    # not in an object of ours. See _tiqr_verify_response() in auth1.

    def verify(
        self,
        token_auth_data: Union[dict,None]=None,
        **kwargs,
        ):
        """ Verify a tiqr response. """
        if not token_auth_data:
            return None
        challenge = token_auth_data.get('challenge')
        session_key = token_auth_data.get('session_key')
        response = token_auth_data.get('response')
        return self.verify_ocra(challenge, session_key, response)

    @object_lock(full_lock=True)
    def _add(
        self,
        callback: JobCallback=default_callback,
        _caller: str="API",
        **kwargs,
        ):
        """ Add a tiqr token. """
        self.used_otp_salt = stuff.gen_secret(32)
        if _caller == "CLIENT":
            return_message = _("NOTE: You have to enroll this tiqr token with your phone to make it usable.")
            callback.send(return_message)
        return self._cache(callback=callback)

    def show_config(self, callback: JobCallback=default_callback, **kwargs):
        if not self.verify_acl("view_public:object"):
            msg = _("Permission denied.")
            return callback.error(msg, exception=PermissionDenied)
        lines = []
        if self.verify_acl("view:secret"):
            lines.append(f'SECRET="{self.secret}"')
        else:
            lines.append('SECRET=""')
        if self.verify_acl("view:ocra_suite"):
            lines.append(f'OCRA_SUITE="{self.ocra_suite}"')
        else:
            lines.append('OCRA_SUITE=""')
        if self.verify_acl("view:identity_id"):
            lines.append(f'IDENTITY_ID="{self.identity_id}"')
        else:
            lines.append('IDENTITY_ID=""')
        if self.verify_acl("view:notification_type"):
            lines.append(f'NOTIFICATION_TYPE="{self.notification_type}"')
        else:
            lines.append('NOTIFICATION_TYPE=""')
        if self.verify_acl("view:notification_address"):
            lines.append(f'NOTIFICATION_ADDRESS="{self.notification_address}"')
        else:
            lines.append('NOTIFICATION_ADDRESS=""')
        lines.append(f'DEPLOYED="{self.deployed}"')
        return Token.show_config(self,
                                config_lines=lines,
                                callback=callback,
                                **kwargs)

    def show(self, **kwargs):
        return self.show_config(**kwargs)
